### ISSUE TITLE
Errors: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by ffauteux** [osiam/stress-tests#4]
Using:
jdk1.8.0_121-1.8.0_121-fcs.x86_64
apache-maven-3.5.0-bin.tar.gz

Latest code base, ran:
mvn clean package
java -jar target/stress-tests-1.0.0-SNAPSHOT.jar http://localhost:8080 &> stress-tests_out.txt

Obtained a large number of "Errors: java.net.SocketTimeoutException: Read timed out"

Using osiam.yaml: 
[osiam.yaml.txt](https://github.com/osiam/stress-tests/files/1278385/osiam.yaml.txt)

osiam output: 
[osiam_out.txt](https://github.com/osiam/stress-tests/files/1278386/osiam_out.txt)

stress tests output:
[stress-tests_out.txt](https://github.com/osiam/stress-tests/files/1278388/stress-tests_out.txt)

stress tests log: 
[stress-tests.log.txt](https://github.com/osiam/stress-tests/files/1278387/stress-tests.log.txt)

The documentation pages mentions Installation instructions which link to a non-existent file.

**Comment by dacrome** [comment]
Hi @ffauteux 

thanks for the report. I will check that in the next days.

Greetz,
David

**Comment by ffauteux** [comment]
Worked around the issue by increasing timeouts in src/main/java/org/osiam/tests/stress/OsiamContext.java:

            OsiamConnector.Builder oConBuilder = new OsiamConnector.Builder()
                    .withEndpoint(OSIAM_ENDPOINT)
                    .setClientId(CLIENT_ID)
                    .setClientSecret(CLIENT_SECRET)
		    .withReadTimeout(50000)
		    .withConnectTimeout(25000);

**Comment by dacrome** [comment]
I close this issue because I thing this fixed your issue. if not, feel free to open this issue again.
