### ISSUE TITLE
Cannot query metrics endpoint

### ISSUE THREAD

**Issue by ffauteux** [osiam/stress-tests#5]
In src/main/java/org/osiam/tests/stress/AggregatorJob.java, line 94, the endpoint for OSIAM metrics is specified as '/monitor/metrics'; according to OSIAM configuration (application.yml), it should be '/management/metrics'.

Also, it seems the example-client used for stress tests does not have the ACTUATOR role required to access these metrics. This can be worked around by running OSIAM with --management.security.enabled=false.

**Comment by dacrome** [comment]
thanks for your issue, but this repository will be archived.
